name = "RKOpt"
uuid = "ead69dcd-9d07-43d4-88a0-2b30abaca44a"
authors = ["Hendrik Ranocha <mail@ranocha.de>"]
version = "0.1.0"

[deps]
Convex = "f65535da-76fb-5f13-bab9-19810c17039a"
ECOS = "e2685f51-7e38-5353-a97d-a921fd2c8199"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
Convex = "0.16"
ECOS = "1.1.2"
LinearAlgebra = "1"
